name: Trashcan
main: fr.shark_zekrom.trashcan.Main
version: 1.6
api-version: 1.13
author: shark_zekrom
description: Trashcan+
commands:
  trashcan:
    description: créer des trashcan facilement
  trash:
    description: trash